import '../globals.css'
import Link from 'next/link'

type Props = {
  params: {
    id: string
  }
}
export const generateMetadata = ({ params }: Props) => {
  return {
    title: '__메타데이터?',
    description: 'Generated by create next app'
  }
}

export default function AdminLayout() {
  return (
    <>
      <Link href={'/about2'}>어바웃 2</Link>
    </>
  )
}
