import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '메타데이터',
  description: 'Generated by create next app'
}

export default function AdminLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/business">business</Link>
          <Link href="/blog">Blog</Link>
        </nav>

        <h1 className="text-4xl font-bold">메타데이터 페이지 입니다! </h1>
        {children}
      </body>
    </html>
  )
}
