import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <ul className="flex gap-2">
            <li>
              <Link href="/about">어바웃</Link>
            </li>
            <li>
              <Link href="/contact">콘택트</Link>
            </li>
            <li>
              <Link href="/blog/1">블로그</Link>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
