import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Image from 'next/image'
import './globals.css'
import Logo from '/public/assets/images/logo.webp'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // if (Math.random() < 0.1) throw new Error('루트에러')

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full h-[60px] bg-black flex justify-center items-center">
          <Image height={100} width={100} src={Logo} alt="Logo"></Image>
        </header>
        {children}
      </body>
    </html>
  )
}
